---
slug: :slack
depends:
  mikutter: 3.6.0-develop
  plugin:
    - world
    - spell
    - settings
    - command
    - score
version: 0.2.0
author: ahiru
name: slack
description: slack for mikutter
