AllCops:
  TargetRubyVersion: 2.3

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 140 characters.'
  StyleGuide: '#140-character-limits'
  Max: 140
  Enabled: true

Style/GlobalVars:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/RescueModifier:
  Enabled: false

FormatString:
  EnforcedStyle: percent

Style/MultilineMethodCallIndentation:
  Enabled: false
